version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    command: "app"
    depends_on:
      - database

  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
